# Test environments configuration for integration tests
environments:
  development:
    description: "Development environment for testing"
    connections:
      - duckdb_local
      - postgres_local
      - sqlite_test
    variables:
      DATA_PATH: "/tmp/dev_data"
      LOG_LEVEL: "DEBUG"
      
  staging:
    description: "Staging environment with cloud connections"
    connections:
      - gcp_test_connection
      - bigquery_test
      - postgres_remote
    variables:
      DATA_PATH: "gs://test-staging-bucket"
      LOG_LEVEL: "INFO"
      
  production:
    description: "Production-like environment"
    connections:
      - gcp_eu_connection
      - snowflake_test
      - redshift_test
    variables:
      DATA_PATH: "gs://production-data-bucket"
      LOG_LEVEL: "WARN"
      
  testing:
    description: "Dedicated testing environment"
    connections:
      - duckdb_memory
      - postgres_local
      - mysql_test
    variables:
      DATA_PATH: "/tmp/test_data"
      LOG_LEVEL: "DEBUG"
      ENABLE_TESTS: "true"