name: Test

on: 
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js with cache
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: npm-ci
      run: npm ci

    - name: Allow unprivileged user namespace (ubuntu)
      if: ${{ startsWith(matrix.os, 'ubuntu') }}
      run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

    - name: Setup Chrome browser (Ubuntu)
      if: ${{ startsWith(matrix.os, 'ubuntu') }}
      uses: browser-actions/setup-chrome@v1

    - name: Setup Chrome browser (macOS)  
      if: ${{ startsWith(matrix.os, 'macos') }}
      uses: browser-actions/setup-chrome@v1

    - name: Setup Chrome browser (Windows)
      if: ${{ startsWith(matrix.os, 'windows') }}
      uses: browser-actions/setup-chrome@v1

    - name: Install dependencies
      run: npm run install:all

    # install bruin cli for linux, mac and windows
    - name: Install Bruin CLI
      run: |
        if [ "${{ runner.os }}" = "Windows" ]; then
          curl -LsSf https://raw.githubusercontent.com/bruin-data/bruin/refs/heads/main/install.sh | sh
        else
          curl -LsSL https://raw.githubusercontent.com/bruin-data/bruin/refs/heads/main/install.sh | sh
        fi
      shell: bash

    - name: Compile
      run: npm run compile

    - name: Build Webview
      run: npm run build:webview

    - name: Run extension tests
      run: |
        if [ "${{ runner.os }}" = "Linux" ]; then
          xvfb-run -a npm run test
        else
          npm run test
        fi
      shell: bash

    - name: Run webview tests
      run: npm run test:webview

    - name: Run integration tests
      run: |
        # Set Chrome path for the extension tester
        if [ "${{ runner.os }}" = "Linux" ]; then
          export CHROME_BIN=$(which google-chrome || which chromium-browser || which chromium)
          echo "Using Chrome at: $CHROME_BIN"
          # Add retry mechanism for flaky tests
          for i in {1..3}; do
            if xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' npm run selenium:run-tests; then
              break
            elif [ $i -eq 3 ]; then
              echo "Integration tests failed after 3 attempts"
              exit 1
            else
              echo "Attempt $i failed, retrying..."
              sleep 5
            fi
          done
        elif [ "${{ runner.os }}" = "macOS" ]; then
          # Try different Chrome locations on macOS
          if [ -f "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" ]; then
            export CHROME_BIN="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
          elif [ -f "/Applications/Chromium.app/Contents/MacOS/Chromium" ]; then
            export CHROME_BIN="/Applications/Chromium.app/Contents/MacOS/Chromium"
          fi
          echo "Using Chrome at: $CHROME_BIN"
          npm run selenium:run-tests
        else
          # Windows - let extension tester handle Chrome detection
          npm run selenium:run-tests
        fi
      shell: bash
      env:
        REPO_ROOT: ${{ github.workspace }}
        CI: true
        HEADLESS: true

    - name: Store UI test logs
      uses: actions/upload-artifact@v4
      if: failure() || cancelled()
      with:
        name: logs-${{ matrix.os }}
        path: test-resources/settings/logs/*

    - name: Store UI Test screenshots
      uses: actions/upload-artifact@v4
      if: failure() || cancelled()
      with:
        name: screenshots-${{ matrix.os }}
        path: test-resources/screenshots/*.png