name: tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm run install:all
    
    - name: Run Playwright tests
      uses: microsoft/playwright-github-action@v1
      with:
        browser: chromium
    - run: npm run test
    - run: npm run test:webview
