name: tests

on: 
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm run install:all

    - name: Run extension tests
      if: runner.os == 'Linux'
      run: xvfb-run -a npm run test

    - name: Run extension tests
      if: runner.os != 'Linux'
      run: npm run test --security-revert
      
    - name: Run webview tests
      run: npm run test:webview
          
    - name: Run integration tests
      run: npm run selenium:run-tests
