name: tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm run install:all
    - name: Run extension tests
      run: npm run test
    - name: Run webview tests
      run: npm run test:webview
    
